-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.2
    hooks:
    -   id: double-quote-string-fixer
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    -   id: trailing-whitespace
    -   id: flake8